### PR TITLE
Product

### PR DESCRIPTION
**Pull request by Rockyraven**
Adding Filter bar and clear button
header and footer
and Adding Car
product-page
d

### CODE REVIEW

**Review by ravikumar0403 — APPROVED** [review]
Looks good to me

**Review by vishalg8454 — APPROVED** [review]
Run prettier once before saving. Rest all looks fine.

**Comment by arjun-computer-geek** [comment]
give some padding to the card

Screenshot_2022-02-20_22-53-05
d

It is not looking good

**Review by arjun-computer-geek — APPROVED** [review]
Rest all looks good to me

**Pull request merged**
